### ISSUE TITLE
提交 Flask 基本目录结构（可以使用空文件）

### ISSUE THREAD

**Issue by LouPlus** [LouPlus/jobplus3-14#4]
参考 `挑战：代码框架及数据库设计` 中的任务一

**Comment by yangbinchen** [comment]
收到了！我今晚完成。

**Comment by yangbinchen** [comment]
已经参考 **挑战：代码框架及数据库设计** 中的任务一，提交了**Flask基本目录结构**
目前的文件还只是一个空文件。
